// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace S1AnimTags
{
#pragma region RPR_Assault_Branch
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_RPR_Assault_End_Air);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_RPR_Assault_End_Ground);
#pragma endregion

#pragma region Player_Common
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_Common_Ground_Dash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_Common_Ground_Dodge);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_Common_Air_Dash);
#pragma endregion

#pragma region Player_RPR
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_RPR_Ground_Weak);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_RPR_Ground_Skill01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_RPR_Ground_Assault);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_RPR_Air_Weak);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_RPR_Air_WeakDive);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_RPR_Air_Skill01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_RPR_Air_Assault);
#pragma endregion

#pragma region Player_SWD
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_SWD_Ground_Weak);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_SWD_Ground_Skill01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_SWD_Ground_Assault);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_SWD_Air_Weak);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_SWD_Air_Skill01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Player_SWD_Air_Assault);
#pragma endregion

#pragma region Boss000
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_Atack00);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_Atack01);
#pragma endregion

#pragma region Enemy001
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Enemy001_Attack01);
#pragma endregion
}
