// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace S1AnimTags
{
#pragma region Assault_Branch
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Female_RPR_AssaultEnd_Air);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Female_RPR_AssaultEnd_Ground);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Female_SWD_AssaultEnd_Air);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Female_SWD_AssaultEnd_Ground);
#pragma endregion

#pragma region SWD_Skill_Branch
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Female_SWD_Skill02_End_Weak);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Female_SWD_Skill02_End_Strong);
#pragma endregion

#pragma region Boss000
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_Encounter);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_Atack00);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_Atack01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_RotateAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_JumpAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_WallKick_Start);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_WallKick_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_SlashThrough);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_PhaseTransition);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_Guard_01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_Guard_02);
#pragma endregion

#pragma region Enemy001
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Enemy001_Attack01);
#pragma endregion
}
