// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace S1UITags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Root_Gameplay);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Root_Lobby);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Cursor);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Fade);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Lobby_HUD);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Lobby_Logo);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Gameplay_HUD);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Monster_HPBar);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Gameplay_DamageNumber);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Menu_Inventory);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Menu_ItemInfo);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Cooldown_Skill01);
}

namespace S1UIResourceTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Tex_Heal);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Tex_Asna_Skill01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Tex_Asna_Skill02);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Tex_Asna_Skill03);

#pragma region Inventory
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_BG_Common);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_BG_Rare);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_BG_Unique);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_BG_Legendary);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_Frame_Common);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_Frame_Rare);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_Frame_Unique);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_Frame_Legendary);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_Effect_Equiped);
#pragma endregion

#pragma region Select
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_Weapon_RPR);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_Weapon_SWD);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Icon_Weapon_DSWD);
#pragma endregion
}
