// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace S1GameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Sprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Turn);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Attack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Jump);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Skill01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Skill02);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Skill03);
}

namespace S1UITags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Root);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Cursor);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Fade);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Lobby_HUD);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Lobby_Logo);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Gameplay_HUD);
}

namespace S1AnimTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_RPR_Weak);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_RPR_AirWeak);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_RPR_Skill01);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Montage_Boss000_Atack00);
}

namespace S1UIResourceTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Tex_Heal);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Tex_Asna_Skill01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Tex_Asna_Skill02);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Tex_Asna_Skill03);
}

namespace S1AbilityTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Attack_Ground);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Attack_Air);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Attack_WeakAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Attack_Skill01);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Attack_Skill02);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Attack_Skill03);

#pragma region Boss000
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss000_Attack00);
#pragma endregion
}

namespace S1Labels
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Label_Preload);
}

namespace S1AssetTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Asset_InputData);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Asset_UIData);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Asset_UIResource);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Asset_Ability);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Asset_Ability_Boss000);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Asset_AnimData);
}

namespace S1StateTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CanNextAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Air);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Air_Used_WeakAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Air_Used_Skill01);
}